# Generated by Django 4.2.5 on 2023-09-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(max_length=5)),
                ('noise_level', models.FloatField()),
                ('trend_coefficients', models.JSONField(default=list)),
                ('missing_percentage', models.FloatField(default=0)),
                ('outlier_percentage', models.FloatField(default=0)),
                ('cycle_frequency', models.IntegerField()),
                ('cycle_amplitude', models.FloatField()),
                ('time_series', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('data_size', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('additive', 'additive'), ('multiplicative', 'multiplicative')], max_length=15)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Running', 'Running'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed')], default='Submitted', max_length=100)),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalityComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amplitude', models.FloatField(default=0)),
                ('phase_shift', models.FloatField(default=0)),
                ('frequency', models.CharField(choices=[('Daily', 'daily'), ('Weekly', 'weekly'), ('Monthly', 'monthly')], max_length=10)),
                ('multiplier', models.FloatField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_components', to='api.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='api.usecase'),
        ),
    ]
